/*
 * Library API Spec
 *
 * This is an api for a library project that will be used in our SLO course.
 *
 * API version: v0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"CreateBook",
		strings.ToUpper("Post"),
		"/v1/book",
		CreateBook,
	},

	Route{
		"DeleteBook",
		strings.ToUpper("Delete"),
		"/v1/book/{bookID}",
		DeleteBook,
	},

	Route{
		"GetBookById",
		strings.ToUpper("Get"),
		"/v1/book/{bookID}",
		GetBookById,
	},

	Route{
		"ListBooks",
		strings.ToUpper("Get"),
		"/v1/book",
		ListBooks,
	},

	Route{
		"UpdateBookById",
		strings.ToUpper("Put"),
		"/v1/book/{bookID}",
		UpdateBookById,
	},
}
